### ISSUE TITLE
之家网页端评论区3天就不可见了，app端还是7天，需要更换评论接口

### ISSUE THREAD

**Issue by rwbymoe** [Tai-Zhou/ITH2Ome#10]

**Comment by Tai-Zhou** [comment]
难度有点高，这个接口（`sn=b685e2b1578a0d64`）用了 MD5，但我不知道用的盐是什么😢

可行的方法应该只有逆向，安卓端用了 360 加固，其他平台我暂时还没尝试。

可预期的时间内很难切换。

**Comment by Tai-Zhou** [comment]
> 有很多妥协方案可以绕过破解

可以具体说说吗👀

**Comment by cantinzing** [comment]
> 难度有点高，这个接口（`sn=b685e2b1578a0d64`）用了 MD5，但我不知道用的盐是什么😢
> 
> 可行的方法应该只有逆向，安卓端用了 360 加固，其他平台我暂时还没尝试。
> 
> 可预期的时间内很难切换。

不是还有小程序吗？

**Comment by Tai-Zhou** [comment]
刚发布了一个版本，两位更新试试。

我注意到相关文章好像也不行了，之后得修一下。但最近确实很忙，还请谅解。

**Comment by Tai-Zhou** [comment]
修复了。因为请求评论的时候没有加 `appver=`，数据里就没有图片信息，所以刚刚没有测出来。

> 这个新接口其实/apiv2换成/api也是通的，但返回结构不一样 所以我在想是不是做个容错，哪个接口正常就拿哪个，省的水库程序员哪天又废弃其中一个

返回结构其实区别不大，v2 没有删除 v1 的字段。但考虑到移动端用的都是 v2 接口，废弃的概率应该很小。同时网页版的接口现在已要求登录，原先的方法也要再调整。容错的这部分工作优先级会比较低。
