### ISSUE TITLE
可以做个翻页或者多获取一些最新消息列表吗？感觉这几条不够看，还有可以加评论显示吗？

### ISSUE THREAD

**Issue by git4fa** [Tai-Zhou/ITH2Ome#3]

**Comment by Tai-Zhou** [comment]
1. 翻页和多获取消息需要之家的（可能是）MD5加密方法，下个版本我先试试刷新时保留消息吧；
2. 评论显示同样需要之家的加密方法。之前也爬过网页版的评论，但比较曲折，我会放上来作为临时方案。

**Comment by git4fa** [comment]
> 1. 翻页和多获取消息需要之家的（可能是）MD5加密方法，下个版本我先试试刷新时保留消息吧；
> 2. 评论显示同样需要之家的加密方法。之前也爬过网页版的评论，但比较曲折，我会放上来作为临时方案。

翻页的话我找从移动端找到了一个可以使用的方法，希望可以帮到你。https://m.ithome.com/api/news/newslistpageget?Tag=&ot=1632901842000&page=0&hitCountAuthority=false，page这些参数没用，将上一次请求的最早的文章的发布时间的时间戳加0使长度为15位数字，就可以请求该时间戳往前的的25篇文章信息，

**Comment by Tai-Zhou** [comment]
> 翻页的话我找从移动端找到了一个可以使用的方法，希望可以帮到你。[https://m.ithome.com/api/news/newslistpageget?Tag=&ot=1632901842000&page=0&hitCountAuthority=false，page这些参数没用，将上一次请求的最早的文章的发布时间的时间戳加0使长度为15位数字，就可以请求该时间戳往前的的25篇文章信息，](https://m.ithome.com/api/news/newslistpageget?Tag=&ot=1632901842000&page=0&hitCountAuthority=false%EF%BC%8Cpage%E8%BF%99%E4%BA%9B%E5%8F%82%E6%95%B0%E6%B2%A1%E7%94%A8%EF%BC%8C%E5%B0%86%E4%B8%8A%E4%B8%80%E6%AC%A1%E8%AF%B7%E6%B1%82%E7%9A%84%E6%9C%80%E6%97%A9%E7%9A%84%E6%96%87%E7%AB%A0%E7%9A%84%E5%8F%91%E5%B8%83%E6%97%B6%E9%97%B4%E7%9A%84%E6%97%B6%E9%97%B4%E6%88%B3%E5%8A%A00%E4%BD%BF%E9%95%BF%E5%BA%A6%E4%B8%BA15%E4%BD%8D%E6%95%B0%E5%AD%97%EF%BC%8C%E5%B0%B1%E5%8F%AF%E4%BB%A5%E8%AF%B7%E6%B1%82%E8%AF%A5%E6%97%B6%E9%97%B4%E6%88%B3%E5%BE%80%E5%89%8D%E7%9A%84%E7%9A%8425%E7%AF%87%E6%96%87%E7%AB%A0%E4%BF%A1%E6%81%AF%EF%BC%8C)

谢谢您！我刚刚发布了一个版本，劳烦您更新一下。评论显示现在还不太理想，之后有接口时我会再更新这一部分。
