### ISSUE TITLE
希望增加列表栏预览是否显示图片的选项

### ISSUE THREAD

**Issue by rwbymoe** [Tai-Zhou/ITH2Ome#4]
![无标题](https://user-images.githubusercontent.com/29307390/168047110-3e8176ea-515c-4227-9983-e7571606b84d.png)

还希望顺便增加评论区头像是否显示的选项，将隐蔽性做到极致

**Comment by Tai-Zhou** [comment]
> 还有如果文章里有flash播放器是加载不了的，希望也能去掉

请问 flash 是指B站视频链接吗，方便的话能否提供一个链接呢？

**Comment by Tai-Zhou** [comment]
`player-selector.js` 中有一段
``` javascript
html5Checker: function () {
    var t = !(/msie [\w.]+/.exec(navigator.userAgent.toLowerCase()) || /Trident/i.test(navigator.userAgent) && /Windows NT 6/.test(navigator.userAgent) || !window.URL);
    if (t) {
        var e = document.createElement("video");
        return e && e.canPlayType && e.canPlayType('video/mp4; codecs="avc1.42001E, mp4a.40.2"')
    }
    return t
}
```
测试后发现 VSCode 并不支持视频播放，[issue](https://github.com/microsoft/vscode/issues/72280) 也佐证了这一点。所以B站视频就设置成了显示标题、封面，用链接跳转的形式。

现在新版已经上架啦，您提到的内容应该都实现了。
