### ISSUE TITLE
图片屏蔽问题

### ISSUE THREAD

**Issue by rwbymoe** [Tai-Zhou/ITH2Ome#5]
又是我，文章id626076，部分图片未屏蔽。
这些图片和普通图片的区别是alt属性里有\n\n，竟然就匹配不到了，神奇

还有vscode里播放视频，我上个月见过一篇能播放的文章，好像是秒拍，已经不知道是哪篇了，在意的话下次遇到跟你说

**Comment by Tai-Zhou** [comment]
大意了，没想到会有\n。

播放视频这个我也留心看看，如果是微博链接的话可能可以试试，B站应该会比较麻烦。
