### ISSUE TITLE
希望增加评论区图片显示

### ISSUE THREAD

**Issue by rwbymoe** [Tai-Zhou/ITH2Ome#7]
现在文章评论区可以发图片了，希望增加评论区图片的显示

**Comment by Tai-Zhou** [comment]
看了一下，有转成 base64 的 URL，理论上挺容易加的。

但我这边的 VSCode 插件调试遇到了点问题😵所以一直鸽着没更新，待我修修

**Comment by Tai-Zhou** [comment]
加上啦，目前的设置是和正文图片宽度一致，如果宽度较小的话一行可以显示多张图片。我在考虑要不要加个缩放比例设置项，例如评论图片是正文宽度的 0.5 倍，此外也想听听您的建议。

**Comment by Tai-Zhou** [comment]
但这样的话对于不同宽度屏幕，图片大小不一，无法统一设置，可能不太好。明天我先改成鼠标悬浮放大试试吧。

**Comment by Tai-Zhou** [comment]
新增了评论图片宽度的设置，图片居中同时鼠标悬浮放大，这样的话应该就没什么问题了。

这个 issue 我就关闭啦。
