### ISSUE TITLE
希望没有最新评论但有热门评论时展示热门评论

### ISSUE THREAD

**Issue by rwbymoe** [Tai-Zhou/ITH2Ome#8]
7天前的文章评论区会被隐藏，只保留热门评论（说实话真的垃圾，过个五一就看不到评论了，1000+评论的文章一个热门评论都没有，论坛反馈过也没用），希望没有最新评论但有热门评论时展示热门评论

**Comment by Tai-Zhou** [comment]
更新了，您再试试。
